version: '3'

services:

  httpie_latest:
    container_name: py27_httpie_latest
    build:
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-teracy/httpie-jwt-auth:py27_httpie_latest_develop}
    command: bash -c ""

  httpie_latest-alpine:
    container_name: py27_httpie_latest-alpine
    build:
      context: .
      dockerfile: Dockerfile-alpine
      args:
        CI_BUILD_ID: ${CI_BUILD_ID}
        CI_BUILD_REF: ${CI_BUILD_REF}
        CI_BUILD_REF_NAME: ${CI_BUILD_REF_NAME}
        CI_BUILD_TIME: ${CI_BUILD_TIME}
        CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}
        CI_PROJECT_NAME: ${CI_PROJECT_NAME}
        CI_BUILD_NUMBER: ${CI_BUILD_NUMBER}
        CI_BUILDER: ${CI_BUILDER}
        HTTPie_VERSION: 0.9.9
    image: ${DOCKER_IMAGE:-teracy/httpie-jwt-auth:py27_httpie_latest-alpine_develop}
    command: bash -c ""
    volumes:
      - .:/opt/app

  httpie_0_9_8:
    container_name: py27_httpie_0_9_8
    build:
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-teracy/httpie-jwt-auth:py27_httpie_0_9_8_develop}
    command: bash -c ""

  httpie_0_9_7:
    container_name: py27_httpie_0_9_7
    build:
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-teracy/httpie-jwt-auth:py27_httpie_0_9_7_develop}
    command: bash -c ""

